# Generated by Django 5.0.1 on 2024-02-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media.photo_product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField(blank=True, choices=[(23, '23'), (23.5, '23.5'), (24, '24'), (24.5, '24.5'), (25, '25'), (25.5, '25.5'), (26, '26'), (26.5, '26.5'), (27, '27'), (27.5, '27.5'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (31.5, '31.5'), (32, '32'), (33, '33.5'), (34, '34'), (34.5, '34.5'), (38, '38'), (38.5, '38.5'), (39, '39')], verbose_name='Размер ноги в cm')),
                ('rus', models.IntegerField(blank=True, choices=[(35, '35'), (36, '36'), (36.5, '36.5'), (37, '37'), (37.5, '37.5'), (38, '38'), (38.5, '38.5'), (39, '39'), (40, '40'), (40.5, '40.5'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (44.5, '44.5'), (45, '45'), (45.5, '45.5'), (46, '46'), (47, '47'), (47.5, '47.5'), (48, '48'), (48.5, '48.5'), (49.5, '49.5'), (50.5, '50.5'), (51.5, '51.5'), (52.5, '52.5'), ('36.5-39', '36.5-39'), ('40-42.5', '40-42.5'), ('42.5-45', '42.5-45'), ('45-47.5', '45-47.5'), ('47.5-49.5', '47.5-49.5'), ('34-37.5', '34-37.5')], verbose_name='Размер ноги в rus')),
                ('eur', models.IntegerField(blank=True, choices=[(36, '36'), (36.5, '36.5'), (37, '37'), (37.5, '37.5'), (38, '38'), (38.5, '38.5'), (39, '39'), (40, '40'), (40.5, '40.5'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (44.5, '44.5'), (45, '45'), (45.5, '45.5'), (46, '46'), (47, '47'), (47.5, '47.5'), (48, '48'), (48.5, '48.5'), (49.5, '49.5'), (50.5, '50.5'), (51.5, '51.5'), (52.5, '52.5'), ('37.5-40', '37.5-40'), ('40-42.5', '40-42.5'), ('42.5-45', '42.5-45'), ('45-47.5', '45-47.5'), ('47.5-49.5', '47.5-49.5'), ('35-37.5', '35-37.5')], verbose_name='Размер ноги в eur')),
                ('us', models.IntegerField(blank=True, choices=[(4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10'), (10.5, '10.5'), (11, '11'), (11.5, '11.5'), (12, '12'), (12.5, '12.5'), (13, '13'), (13.5, '13.5'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXS', 'XXS')], verbose_name='Размер ноги в us')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='products.product')),
            ],
        ),
    ]
